name: Resource Groups Terraform CI/CD

on:
  push:
    branches:
      - main
      - release/dev
  pull_request:
    branches:
      - main

jobs:
  terraform:
    name: 'Terraform Lint, Security Check, and Deploy (RG)'
    runs-on: ubuntu-latest

    env:
      AWS_REGION: 'us-east-1'
      TF_VERSION: '1.4.0'
      TFLINT_VERSION: '0.46.1'
      TFSEC_VERSION: '1.28.1'

    defaults:
      run:
        working-directory: resource-groups

    steps:
    - name: 'Checkout GitHub repository'
      uses: actions/checkout@v2

    # - name: Configure AWS credentials
    #   uses: aws-actions/configure-aws-credentials@v1
    #   with:
    #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #     aws-region: ${{ env.AWS_REGION }}

    # Write variables.auto.tfvars dynamically in the workflow
    - name: Generate variables.auto.tfvars
      run: |
        echo "aws_access_key_id = \"${{ secrets.AWS_ACCESS_KEY_ID }}\"" >> variables.auto.tfvars
        echo "aws_secret_access_key = \"${{ secrets.AWS_SECRET_ACCESS_KEY }}\"" >> variables.auto.tfvars
        echo "ip_whitelist = \"${{ secrets.IP_WHITELIST }}\"" >> variables.auto.tfvars

    - name: 'Set up Terraform with AWS credentials'
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: ${{ env.TF_VERSION }}
        cli_config_credentials_token: ${{ secrets.TFC_API_TOKEN }}
      # env:
      #   AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #   AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #   AWS_REGION: ${{ env.AWS_REGION }}

#     - name: 'Terraform Cloud login'
#       env:
#         TFC_API_TOKEN: ${{ secrets.TFC_API_TOKEN }}
#       run: |
#         mkdir -p ~/.terraform.d
#         cat > ~/.terraform.d/credentials.tfrc.json <<'EOF'
#         {
#           "credentials": {
#             "app.terraform.io": {
#               "token": "${TFC_API_TOKEN}"
#             }
#           }
#         }
#         EOF

    - name: 'Install TFLint'
      run: |
        curl -sLo tflint.zip https://github.com/terraform-linters/tflint/releases/download/v${{ env.TFLINT_VERSION }}/tflint_linux_amd64.zip
        unzip tflint.zip -d /usr/local/bin/
        tflint --version

    - name: 'Install tfsec'
      run: |
        curl -sLo tfsec https://github.com/aquasecurity/tfsec/releases/download/v${{ env.TFSEC_VERSION }}/tfsec-linux-amd64
        chmod +x tfsec
        mv tfsec /usr/local/bin/
        tfsec --version
      
    # Debug step: Check environment variables
    # - name: 'Debug Environment Variables'
    #   run: |
    #     echo "Available environment variables:"
    #     env | sort
    #   env: # Pass the environment variables you care about to ensure they exist
    #       AWS_REGION: ${{ env.AWS_REGION }}
    #       AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #       AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: 'Terraform Init'
      run: terraform init
      env:
          TFC_TOKEN: ${{ secrets.TFC_API_TOKEN }}

    - name: 'Terraform Format'
      run: terraform fmt

    - name: 'Terraform Validate'
      run: terraform validate

    - name: 'TFLint'
      run: |
        tflint --init
        tflint

    - name: 'tfsec'
      run: tfsec .

    - name: 'Terraform Plan'
      #run: terraform plan -var "aws_access_key_id=${{ secrets.AWS_ACCESS_KEY_ID }}" -var "aws_secret_access_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}"
      run: terraform plan
#      env:
#          TFC_TOKEN: ${{ secrets.TFC_API_TOKEN }}
#          AWS_REGION: ${{ env.AWS_REGION }}
    - name: 'Terraform Apply'
      if: github.ref == 'refs/heads/main'
      run: terraform apply -auto-approve
      # env:
      #     AWS_REGION: ${{ env.AWS_REGION }}
      #     TFC_TOKEN: ${{ secrets.TFC_API_TOKEN }}

    - name: 'clean up secrets'
      run: rm variables.auto.tfvars
